# Continuous Integration/Delivery (CI/CD) Workflow 
# By Zhean Ganituen 
# DB-Poultry Project 
# 
# For:          CSSWENG, Mr. Mar Hererra 
#               STSWENG, Dr. Alon Alvin 
#
# Last Updated: September 1, 2025

name: CI (Java, PostgreSQL)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: SETUP# Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: SETUP# PostgreSQL (install via Choco)
      run: choco install postgresql14 --params '/Password:db_poultry_test' -y

    - name: SETUP# PostgreSQL (start)
      run: net start postgresql-x64-14

    - name: SETUP# PostgreSQL (init)
      run: |
        psql -U postgres -c "CREATE DATABASE db_poultry_test;"
        psql -U postgres -c "CREATE USER db_poultry_test WITH PASSWORD 'db_poultry_test';"
        psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE db_poultry_test TO db_poultry_test;"
      env:
        PGPASSWORD: db_poultry_test

    - name: BUILD
      run: gradle build
      env:
        DB_URL: jdbc:postgresql://localhost:5432/db_poultry_test
        DB_USERNAME: db_poultry_test
        DB_PASSWORD: db_poultry_test

    - name: PACK
      run: gradle jpackage

    - name: DEPLOY# Make GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v5.0.${{ github.run_number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: DEPLOY# Upload Package
      uses: softprops/action-gh-release@v2
      with:
        files: build/installer/*
