# CI/CD for DB-Poultry
# Zhean Ganituen
# DB-Poultry Development Team
#
# FOR:
#   CSSWENG, Mar Hererra
#   STSWENG, Dr. Alvin Alon
#
# LAST UPDATE:
#   September 1, 2025

name: CI/CD (FatJar + PostgreSQL)

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: db_poultry_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Wait for PostgreSQL
        run: |
          for i in {1..10}; do
            pg_isready -h localhost -p 5432 -U postgres && break
            echo "Waiting for PostgreSQL..."
            sleep 5
          done

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build project (with fatJar)
        run: ./gradlew clean fatJar
        env:
          DB_URL: jdbc:postgresql://localhost:5432/db_poultry_test
          DB_USERNAME: postgres
          DB_PASSWORD: postgres

      - name: List app/build/libs directory
        run: ls -l app/build/libs || echo "UH OH~ app/build/libs does not exist"

      - name: Create Git tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag v5.0.${{ github.run_number }}
          git push origin v5.0.${{ github.run_number }}

      - name: Prepare test report directory
        if: always()
        run: |
          if [ ! -d build/reports/tests/test ]; then
            mkdir -p build/reports/tests/test
            echo "<h1>No test report available</h1><p>Build failed before tests ran.</p>" > build/reports/tests/test/index.html
          fi

      - name: Deploy JUnit test reports to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/reports/tests/test
          publish_branch: gh-pages