name: CI (Java, PostgreSQL)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: db_poultry_test
          POSTGRES_USER: db_poultry_test
          POSTGRES_PASSWORD: db_poultry_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Gradle
      run: gradle build
      env:
        DB_URL: jdbc:postgresql://localhost:5432/db_poultry_test
        DB_USERNAME: db_poultry_test
        DB_PASSWORD: db_poultry_test
